[package]
name = "visgen_graph"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indextree = "4.3.1"
nannou = "0.17.1"
nannou_osc = "0.17.0"
wgpu = "0.9.0"